<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7670" started-at="2021-02-12T06:03:49 IST" finished-at="2021-02-12T06:03:57 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7670" started-at="2021-02-12T06:03:49 IST" finished-at="2021-02-12T06:03:57 IST">
      <class name="com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest@10bbd20a]" name="launchBrowser" is-config="true" duration-ms="10878" started-at="2021-02-12T06:03:38 IST" finished-at="2021-02-12T06:03:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest@10bbd20a]" name="launchApplication" is-config="true" duration-ms="5580" started-at="2021-02-12T06:03:49 IST" finished-at="2021-02-12T06:03:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="initilazePages()[pri:0, instance:com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest@10bbd20a]" name="initilazePages" is-config="true" duration-ms="153" started-at="2021-02-12T06:03:55 IST" finished-at="2021-02-12T06:03:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilazePages -->
        <test-method status="FAIL" signature="verifyABTestLIink()[pri:0, instance:com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest@10bbd20a]" name="verifyABTestLIink" duration-ms="1788" started-at="2021-02-12T06:03:55 IST" finished-at="2021-02-12T06:03:57 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [A/B Test Control] but found [A/B Test Variant 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [A/B Test Control] but found [A/B Test Variant 1]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest.verifyABTestLIink(VerifyABTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyABTestLIink -->
        <test-method status="PASS" signature="killSession()[pri:0, instance:com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest@10bbd20a]" name="killSession" is-config="true" duration-ms="167" started-at="2021-02-12T06:04:02 IST" finished-at="2021-02-12T06:04:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- killSession -->
      </class> <!-- com.automation.PracticeSeleniumFramework.ABTest.VerifyABTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
